package micronaut.stream.message.size

import io.micronaut.http.MediaType
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.http.sse.Event
import io.reactivex.Observable

@Controller
class StreamController {

  private List strings = [
      'AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|',
      'AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|',
      'AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|',
      'AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|',
      'AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|AAAAAAAAAAAAAAAAAAA|'
  ]

  @Get(uri = "/stream", produces = MediaType.TEXT_EVENT_STREAM)
  Observable<Event<String>> infiniteStrings() {
    return Observable.fromIterable(strings.collect { Event.of(it) })
  }
}
